### PR TITLE
OCPBUGS-34297: Updating golang-github-prometheus-alertmanager-contain…

### PR DESCRIPTION
**Pull request by machine424**
…er image to be consistent with ART for 4.17

Reconciling with https://github.com/openshift/ocp-build-data/tree/4c1326094222f9209876f06833179a1b9178faf7/images/golang-github-prometheus-alertmanager.yml

Supersedes https://github.com/openshift/prometheus-alertmanager/pull/92

### CODE REVIEW

**Comment by rexagod** [comment]
/lgtm

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml#L13-L20 will be updated by the bot IIRC.

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
