### PR TITLE
Bump to v0.17.0

### PR DESCRIPTION
**Pull request by simonpasquier**
Diff between upstream and this PR:
https://github.com/prometheus/alertmanager/compare/v0.17.0...simonpasquier:aos-bump-0.17.0

Diff between upstream and the current master:
https://github.com/prometheus/alertmanager/compare/v0.16.2...openshift:39c2c111ea818cd16dbd11e31cc682cf2b4042d3

### CODE REVIEW

**Comment by simonpasquier** [comment]
cc @mxinden

**Comment by pgier** [comment]
Do we still want to keep the .spec file updated?  It still says 0.16.2.

**Comment by simonpasquier** [comment]
Right so AFAICT the spec and systemd files aren't needed anymore.
I've submitted separate PRs to get rid of them:
https://github.com/openshift/prometheus-alertmanager/pull/24
https://github.com/openshift/prometheus/pull/30
https://github.com/openshift/node_exporter/pull/30

**Pull request merged**
