### PR TITLE
OCPBUGS-12506: update golang.org/x/net

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by danielmellado** [comment]
PR lgtm, seems like CI is failing for a totally unrelated thing (image missing yamllint)

```
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin)
```

**Comment by simonpasquier** [comment]
@danielmellado I missed some files in the vendor/ directory but this is now fixed.

**Review by slashpai — APPROVED** [review]
/lgtm

**Pull request merged**
